# Generated by Django 4.2.7 on 2023-11-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
